apiVersion: v1
kind: Service
metadata:
  name: survey-backend-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: survey-backend
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30086
